# docker-compose.yml

version: '3.9'

services:
  php-apache:
    build: .
    container_name: php7_apache_container
    ports:
      - "8082:80"
    volumes:
      - ./php:/var/www/html/backend   # PHP backend files
      # Remove the frontend volume mapping if not needed for development
      # - ./dist/web:/var/www/html      # Angular build files and frontend assets
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped
